In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [7]:
df = pd.read_csv('C:/Users/Adam Warlock/OneDrive/Desktop/ML Model/Tweets.csv')

In [8]:
df = df[['text', 'airline_sentiment']]
df.columns = ['text', 'sentiment']

In [9]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    return text

In [10]:
df['text'] = df['text'].apply(clean_text)

In [11]:
X = df['text']
y = df['sentiment']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [14]:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [15]:
y_pred = model.predict(X_test_tfidf)

In [16]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7387295081967213

Classification Report:
               precision    recall  f1-score   support

    negative       0.73      0.98      0.84      1889
     neutral       0.73      0.23      0.35       580
    positive       0.88      0.38      0.53       459

    accuracy                           0.74      2928
   macro avg       0.78      0.53      0.57      2928
weighted avg       0.75      0.74      0.69      2928


Confusion Matrix:
 [[1856   25    8]
 [ 434  131   15]
 [ 260   23  176]]


In [17]:
def predict_sentiment(text):
    text = clean_text(text)
    vec = vectorizer.transform([text])
    return model.predict(vec)[0]


In [18]:
print(predict_sentiment("I love this airline, great service"))
print(predict_sentiment("Terrible flight, very delayed and bad staff"))

positive
negative


In [24]:
print(predict_sentiment("Excellent service and smooth journey"))
print(predict_sentiment("Flight was on time and very comfortable"))

positive
positive
